version: 2

jobs:
  build1:
    docker:
      - image: buildpack-deps:trusty
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD
      - image: postgres:9.4.1
        auth:
          username: mydockerhub-user 
          password: $DOCKERHUB_PASSWORD
        environment:
          POSTGRES_USER: root
  build2:
    machine:
      image: ubuntu-2004:202010-01
  build3:
    macos:
      xcode: "11.3.0"
workflows:
  jobs:
    build_and_test:
      - build1
      - build2
      # - build3
