version: 2

jobs:
  build:
    docker:
      - image: circleci/php:7.2-stretch

    steps:
      - checkout
  build1:
    docker:
      - image: buildpack-deps:trusty
      - image: postgres:9.4.1
    steps:
      - checkout
  build2:
    machine:
      image: ubuntu-2004:202010-01
    steps:
      - checkout
  build3:
    macos:
      xcode: "11.3.0"
    steps:
      - checkout

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - build1:
          requires:
          - build
      - build2:
          requires:
          - build1
      - hold:
          type: approval